name: Test

on: [ push, pull_request ]

jobs:
    Consistency:
        name: 'Consistency'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2
                    coverage: none

            -   name: Setup authentication for Composer
                run: composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

            -   name: "Extract tag, branch, version from GITHUB_REF"
                id: "github-ref"
                run: |
                    echo "::set-output name=tag::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/(.*)$#\1#p')"
                    echo "::set-output name=branch::$(echo $GITHUB_REF | sed -E -n 's#^refs/heads/(.*)$#\1#p')"
                    echo "::set-output name=version::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/v?([0-9]+\.)([0-9]+\.)([0-9]+)#\1\2\3#p')"

            -   name: Compare tag version with committed version
                if: steps.github-ref.outputs.version != ''
                run: |
                    composer set-version $(echo ${{ steps.github-ref.outputs.tag }} | sed s/^v//g)
                    test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";

            -   name: Compare extension composer.json with main composer.json
                run: |
                    composer extension-verify-composer-json

            -   name: Build extension artifact
                run: |
                    composer extension-release

    Tests:
        name: 'T3 ${{ matrix.typo3 }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
        runs-on: ubuntu-18.04

        strategy:
            fail-fast: false
            matrix:
                typo3: [ '^10.4.1' ]
                php: [ '7.2', '7.3', '7.4' ]
                dependency-version: [ lowest, stable ]
                experimental: [ false ]
                include:
                    -   php: 7.4
                        typo3: '~11.3.1'
                        dependency-version: stable
                        experimental: false
                    -   php: 8.0
                        typo3: '~11.3.1'
                        dependency-version: stable
                        experimental: false
                    -   php: 7.4
                        typo3: dev-master
                        dependency-version: stable
                        experimental: true
                    -   php: 8.0
                        typo3: dev-master
                        dependency-version: stable
                        experimental: true

        continue-on-error: ${{ matrix.experimental }}

        steps:
            -   name: Start database server
                run: sudo /etc/init.d/mysql start

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    coverage: none

            -   name: Setup authentication for Composer
                run: composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

            -   name: Environment Check
                run: |
                    php --version
                    composer --version

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install
                run: |
                    export COMPOSER_ROOT_VERSION=6.6.0
                    composer require --no-update \
                          typo3/cms-backend="${{ matrix.typo3 }}" \
                          typo3/cms-core="${{ matrix.typo3 }}" \
                          typo3/cms-extbase="${{ matrix.typo3 }}" \
                          typo3/cms-extensionmanager="${{ matrix.typo3 }}" \
                          typo3/cms-fluid="${{ matrix.typo3 }}" \
                          typo3/cms-frontend="${{ matrix.typo3 }}" \
                          typo3/cms-install="${{ matrix.typo3 }}" \
                          typo3/cms-recordlist="${{ matrix.typo3 }}"
                    composer update --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction
                    git checkout composer.json

            -   name: Lint
                run: .Build/bin/parallel-lint --exclude .Build .

            # This fails when command reference is not up to date
            -   name: Test Command Reference
                run: |
                    ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)"

            -   name: Test Install
                run: './typo3cms install:setup --database-host-name=127.0.0.1 --database-user-name=root --database-user-password=root --database-name=typo3_test_ci_github  --admin-user-name=admin --admin-password=password --no-interaction -vvv'

            -   name: Test
                run: .Build/bin/phpunit
